#pragma once

struct SDL_Cursor *createCursorFromImage(const char *image[]);

static const char *g_CursorArrowImage[] =
{
  "X                               ",
  "XX                              ",
  "X.X                             ",
  "X..X                            ",
  "X...X                           ",
  "X....X                          ",
  "X.....X                         ",
  "X......X                        ",
  "X.......X                       ",
  "X........X                      ",
  "X.........X                     ",
  "X..........X                    ",
  "X......XXXXXX                   ",
  "X...X..X......                  ",
  "X..X.X..X                       ",
  "X.X..X..X.                      ",
  "XX..  X..X                      ",
  "X..   X..X.                     ",
  " .     XX..                     ",
  "        ..                      ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "0, 0"
};

static const char *g_CursorMoveImage[] =
{
  "          X                     ",
  "         X.X                    ",
  "        X...X                   ",
  "       X.....X                  ",
  "      XXXX.XXXX                 ",
  "       ..X.X....                ",
  "    X    X.X.   X               ",
  "   XX.   X.X.   XX              ",
  "  X.X.   X.X.   X.X             ",
  " X..XXXXXX.XXXXXX..X            ",
  "X...................X           ",
  " X..XXXXXX.XXXXXX..X..          ",
  "  X.X....X.X....X.X..           ",
  "   XX.   X.X.   XX..            ",
  "    X.   X.X.   X..             ",
  "     .   X.X.    .              ",
  "      XXXX.XXXX                 ",
  "       X.....X..                ",
  "        X...X..                 ",
  "         X.X..                  ",
  "          X..                   ",
  "           .                    ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "10, 10"
};

static const char *g_CursorResizeVImage[] =
{
  "          X                     ",
  "         X.X                    ",
  "        X...X                   ",
  "       X.....X                  ",
  "      X.......X                 ",
  "     XXXXX.XXXXX                ",
  "      ...X.X.....               ",
  "         X.X.                   ",
  "         X.X.                   ",
  "         X.X.                   ",
  "         X.X.                   ",
  "         X.X.                   ",
  "         X.X.                   ",
  "         X.X.                   ",
  "         X.X.                   ",
  "     XXXXX.XXXXX                ",
  "      X.......X..               ",
  "       X.....X..                ",
  "        X...X..                 ",
  "         X.X..                  ",
  "          X..                   ",
  "           .                    ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "10, 10"
};

static const char *g_CursorResizeHImage[] =
{
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "     X         X                ",
  "    XX.        XX               ",
  "   X.X.        X.X              ",
  "  X..X.        X..X             ",
  " X...XXXXXXXXXXX...X            ",
  "X...................X           ",
  " X...XXXXXXXXXXX...X..          ",
  "  X..X.........X..X..           ",
  "   X.X.        X.X..            ",
  "    XX.        XX..             ",
  "     X.        X..              ",
  "      .         .               ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "10, 10"
};

static const char *g_CursorResizeLRImage[] =
{
  "XXXXXXXX                        ",
  "X.....X..                       ",
  "X....X..                        ",
  "X...X..                         ",
  "X..X.X                          ",
  "X.X.X.X                         ",
  "XX.. X.X                        ",
  "X..   X.X                       ",
  " .     X.X                      ",
  "        X.X     X               ",
  "         X.X   XX.              ",
  "          X.X X.X.              ",
  "           X.X..X.              ",
  "            X...X.              ",
  "           X....X.              ",
  "          X.....X.              ",
  "         XXXXXXXX.              ",
  "          ........              ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "8, 8"
};

static const char *g_CursorResizeRLImage[] =
{
  "         XXXXXXXX               ",
  "          X.....X.              ",
  "           X....X.              ",
  "            X...X.              ",
  "           X.X..X.              ",
  "          X.X.X.X.              ",
  "         X.X.. XX.              ",
  "        X.X..   X.              ",
  "       X.X..     .              ",
  "X     X.X..                     ",
  "XX   X.X..                      ",
  "X.X X.X..                       ",
  "X..X.X..                        ",
  "X...X..                         ",
  "X....X                          ",
  "X.....X                         ",
  "XXXXXXXX                        ",
  " ........                       ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "                                ",
  "8, 8"
};
